apiVersion: v1
kind: Namespace
metadata:
  name: lab4

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lab4
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          value: "primellin"
        - name: REACT_APP_COMPANY_NAME
          value: "ITMO"
        ports:
          - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: lab4
  labels:
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    tier: frontend
