apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: ippool-rack0
spec:
  cidr: 192.168.0.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: rack == "0"

---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: ippool-rack1
spec:
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: rack == "1"
