apiVersion: v1
kind: Namespace
metadata:
  name: secret-frontend

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: secret-frontend
data:
  react_app_username: "primellin"
  react_app_company_name: "ITMO"

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: secret-frontend
  namespace: secret-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: secret-frontend
  template:
    metadata:
      labels:
        tier: secret-frontend
    spec:
      containers:
      - name: secret-frontend
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: config
              key: react_app_username
        - name: REACT_APP_COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: config
              key: react_app_company_name
        ports:
          - containerPort: 3000
            name: http
---

apiVersion: v1
kind: Service
metadata:
  name: secret-frontend
  namespace: secret-frontend
  labels:
    tier: secret-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
  selector:
    tier: secret-frontend
